version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: EclipseTasks.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=5000
        ports:
            - 5000:5000
        
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Eclipseworks_user_sa
            - MSSQL_PID=Express